# Generated by Django 3.2.4 on 2021-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_auto_20210621_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prev30',
            name='data',
        ),
        migrations.AddField(
            model_name='prev30',
            name='date',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='prev30',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prev30',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='prev30',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
