# Generated by Django 3.2.4 on 2021-11-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0003_auto_20210621_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='astronomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=1000)),
                ('dob', models.DateField(default=None)),
                ('dod', models.DateField(default=None)),
                ('books', models.JSONField(default=None)),
                ('info', models.TextField(default=None)),
            ],
        ),
    ]
