# Generated by Django 3.2.4 on 2021-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0004_astronomers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronomers',
            name='books',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='dod',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='astronomers',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
