# Generated by Django 3.2.4 on 2021-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0005_auto_20211109_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronomers',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='astronomers',
            name='dod',
        ),
        migrations.AddField(
            model_name='astronomers',
            name='yob',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='astronomers',
            name='yod',
            field=models.IntegerField(default=0),
        ),
    ]
