# Generated by Django 3.2.4 on 2021-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0006_auto_20211109_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomers',
            name='image_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='astronomers',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
