# Generated by Django 3.2.4 on 2021-11-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0007_auto_20211109_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('image_link', models.TextField(default='')),
                ('yob', models.CharField(default='', max_length=5)),
                ('yod', models.CharField(default='', max_length=5)),
                ('books', models.JSONField(default='')),
                ('summary', models.TextField(default='')),
                ('info', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='astronomers',
        ),
    ]
