# Generated by Django 3.2.4 on 2021-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0008_auto_20211110_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronomer',
            old_name='info',
            new_name='wiki_link',
        ),
    ]
